name: bagel CI

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Make binary
      run: |
        make bagel
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bagel
        path: ./bagel
